#!/usr/bin/env Rscript
# ==============================================================================
# SCRIPT:   R/15_extract_taxon_impact.R
# PURPOSE:  Defensively extract per-study per-taxon impact tables from the
#           ANALYSE_REAL .rds files and emit them as flat CSVs, so users can
#           inspect/sort/share without needing R.
#
# INPUTS:   *_results.rds files in the current directory (one per study)
# OUTPUTS:  <study>__<field>.csv — one per data frame found in the .rds.
#           A README.txt explaining the layout.
#
# DESIGN:   The .rds structure varies by SeCAT version, so this script
#           defensively walks every named element of each .rds list and writes
#           anything that looks like a data frame to CSV. Non-data-frame
#           elements are summarised in a manifest. Robust to schema drift.
# ==============================================================================

suppressPackageStartupMessages({
    library(utils)
})

rds_files <- list.files(pattern = "_results\\.rds$", full.names = TRUE)
if (length(rds_files) == 0) {
    cat("No *_results.rds files found in current directory.\n")
    quit(status = 0)
}

cat(sprintf("Found %d per-study .rds files\n", length(rds_files)))
manifest <- list()

for (f in rds_files) {
    study <- sub("_results\\.rds$", "", basename(f))
    obj <- tryCatch(readRDS(f), error = function(e) {
        cat(sprintf("  x %s: failed to read .rds (%s)\n", study, e$message))
        NULL
    })
    if (is.null(obj)) next

    fields_written <- c()

    if (is.list(obj) && !is.null(names(obj))) {
        for (name in names(obj)) {
            x <- obj[[name]]
            outfile <- sprintf("%s__%s.csv", study, name)

            tryCatch({
                if (is.data.frame(x)) {
                    write.csv(x, outfile, row.names = FALSE)
                    fields_written <- c(fields_written, name)
                } else if (is.matrix(x) || is.array(x)) {
                    write.csv(as.data.frame(x), outfile, row.names = TRUE)
                    fields_written <- c(fields_written, paste0(name, " (matrix)"))
                } else if (is.list(x) && !is.null(names(x))) {
                    for (subname in names(x)) {
                        y <- x[[subname]]
                        if (is.data.frame(y)) {
                            subfile <- sprintf("%s__%s__%s.csv", study, name, subname)
                            write.csv(y, subfile, row.names = FALSE)
                            fields_written <- c(fields_written, sprintf("%s/%s", name, subname))
                        }
                    }
                }
            }, error = function(e) {
                cat(sprintf("  ! %s.%s: write failed (%s)\n", study, name, e$message))
            })
        }
    }

    cat(sprintf("  v %s: %d fields extracted (%s)\n",
                study, length(fields_written),
                paste(fields_written, collapse = ", ")))
    manifest[[study]] <- fields_written
}

readme_lines <- c(
    "# Per-study taxon-impact CSVs",
    "",
    "These files were extracted by R/15_extract_taxon_impact.R from the",
    "per-study *_results.rds files emitted by ANALYSE_REAL.",
    "",
    "## Naming convention",
    "",
    "  <study>__<field>.csv         - flat data frame from the top of the .rds",
    "  <study>__<field>__<sub>.csv  - flat data frame nested one level down",
    "",
    "## Fields extracted per study",
    ""
)
for (study in names(manifest)) {
    readme_lines <- c(readme_lines,
                      sprintf("- %s:", study),
                      paste0("  - ", manifest[[study]]),
                      "")
}
readme_lines <- c(readme_lines,
    "## If a field you expect isn't here",
    "",
    "The .rds may have been generated by an older SeCAT version with a",
    "different structure. Load the .rds in R directly to inspect:",
    "",
    "  res <- readRDS(\"<study>_results.rds\")",
    "  str(res, max.level = 2)",
    "",
    "Then extend R/15_extract_taxon_impact.R to handle the new field names.")
writeLines(readme_lines, "README.txt")

cat("\nDone. CSVs and README.txt written to current directory.\n")
